# Generated by Django 5.0.14 on 2026-05-17 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='meta_description',
            field=models.TextField(blank=True, help_text='Description pour les moteurs de recherche (SEO)', max_length=160, verbose_name='Méta-description'),
        ),
        migrations.AddField(
            model_name='article',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Titre pour les moteurs de recherche (SEO)', max_length=100, verbose_name='Méta-titre'),
        ),
    ]
