# Generated by Django 5.0.14 on 2026-05-23 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weblog', '0002_article_meta_description_article_meta_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='views_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Nombre de vues'),
        ),
    ]
