# Generated by Django 5.0.14 on 2026-05-24 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weblog', '0003_article_views_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Brouillon'), ('SUBMITTED', 'En attente de validation'), ('PUBLISHED', 'Publié'), ('ARCHIVED', 'Archivé')], default='DRAFT', max_length=10, verbose_name='Statut'),
        ),
    ]
