# Generated by Django 5.0.14 on 2026-05-23 17:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_facebook_url_customuser_linkedin_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='show_recruitment_section',
            field=models.BooleanField(default=True, verbose_name='Afficher la section recrutement'),
        ),
        migrations.CreateModel(
            name='PromotionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_role', models.CharField(choices=[('VISITOR', 'Visiteur'), ('CONTRIBUTOR', 'Contributeur'), ('WRITER', 'Rédacteur'), ('EDITOR', 'Éditeur'), ('ADMIN', 'Administrateur')], max_length=20, verbose_name='Rôle demandé')),
                ('message', models.TextField(max_length=1000, verbose_name='Lettre de motivation')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('APPROVED', 'Approuvée'), ('REJECTED', 'Rejetée')], default='PENDING', max_length=10, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Demande de promotion',
                'verbose_name_plural': 'Demandes de promotion',
                'ordering': ['-created_at'],
            },
        ),
    ]
