# Generated by Django 5.0.14 on 2026-05-23 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_show_recruitment_section_promotionrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('VISITOR', 'Visiteur'), ('CONTRIBUTOR', 'Contributeur'), ('WRITER', 'Rédacteur'), ('EDITOR', 'Éditeur'), ('ADMIN', 'Administrateur')], default='CONTRIBUTOR', max_length=20, verbose_name='Rôle'),
        ),
    ]
